apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: bootcamp
data:
  01-create-dbs.sql: |
    CREATE DATABASE user_db;
    CREATE DATABASE bootcamp_db;
    CREATE DATABASE registration_db;
    CREATE DATABASE showcase_db;
